### ISSUE TITLE
what connection (if any) with parallelism & places?

### ISSUE THREAD

**Issue by mbutterick** [dedbox/racket-event-lang#12]
The small amount of event programming I've done so far uses events to manage jobs being handled in parallel by multiple Racket places. The `event-lang` docs show examples of multi-threaded operation, though of course in Racket threads are not actually parallel. Is there a natural way of integrating place-based parallelism into `event-lang`, or is it more a matter of personal taste?

**Comment by dedbox** [comment]
Thanks for the question!

Events are a general-purpose *synchronous programming* model for concurrency. Threads are just an easy source of self-contained examples because they provide concurrency. Events can be used for reactive programming, co-routines, and the kinds of things Python or Javascript does with `async`/`await` or that C does with `select`. I've used events as streams and in promises, lazy language constructs, actor models, multi-party messaging primitives, and generic message routing infrastructure.

Places and place channels can be used as synchronizable events.
```racket
#lang racket/base

(require racket/place)

(provide main)

(define (main)
  (define p (place pch
              (place-channel-put pch 123)
              (sync pch)))
  (sync p)
  (place-channel-put p 456)
  (void (place-wait p)))
```
Places are a little weird because one end of the exchange is mediated by a place channel (`pch`) and the other end by a place (`p`), and places will starve the system to death in an infinite regression if they're defined at the top of a module. Wow. So let's look at channels first.

Channels can also be used as synchronizable events. They're unbuffered, which means either side of a channel-mediated exchange will block until both sides are ready. Place channels *are* buffered, so they behave more like an `async-channel` (or thread mailbox) than a `channel` because the sender usually doesn't block.

With threads and channels, the "thread pool" or worker-supervisor technique is straight forward:
```racket
#lang racket/base

(define num-workers 10)
(define num-orders  100)
(define num-batches (/ num-orders num-workers))

(define  in-ch (make-channel))
(define out-ch (make-channel))

(define (worker-thread)
  (define num (channel-get in-ch))
  (sleep (random))  ; for up to 1 full second
  (channel-put out-ch num)
  (worker-thread))

(define workers (build-list num-workers (λ _ (thread worker-thread))))

(for ([j num-batches])
  (for ([i num-workers]) (channel-put in-ch (+ i (* j num-workers))))
  (for ([_ num-workers]) (channel-get out-ch)))
```

First, the supervisor makes a pair of channels: `in-ch` and `out-ch`. Then, it spawns a few workers with the channels in scope. Each worker takes an order from `in-ch`, does some work, then puts its result into `out-ch`. The supervisor gets everything started by putting an order for each worker into `in-ch`. While the workers are working, the supervisor waits for results to arrive through `out-ch` and then handles them one at a time.

Each worker will be busy (`sleep`ing) for up to 1 second and I'm running them in batches of 10, so I expect the run time to be around 10 seconds. Sure enough, the time to process all 100 orders with 10 workers is around 9 seconds on my computer.

Every thread comes with a thread mailbox, which is pretty much a built-in `async-channel` with a different API. If I use thread mailboxes instead of `in-ch`, I can lean on them to buffer orders instead of having to split them into batches myself.
```racket
#lang racket/base

(define num-workers 10)
(define num-orders  100)

(define out-ch (make-channel))

(define (worker-thread)
  (define num (thread-receive))
  (sleep (random))  ; for up to 1 full second
  (channel-put out-ch num)
  (worker-thread))

(define workers
  (build-list num-workers (λ _ (thread worker-thread))))

(for ([i num-orders]
      [worker (apply append (build-list 10 (λ _ workers)))])
  (thread-send worker i))
(for ([_ num-orders]) (channel-get out-ch))
```

In the previous version, splitting the orders into 10 batches meant the whole thread pool had to be fully synchronized 10 times. This version takes around 7 seconds to process 100 orders on my computer with 10 threads. It never tries to synchronize the whole pool at once, but the way it assigns orders to workers is arbitrary. If I want everything to wait as little as possible, I can re-introduce `in-ch` as an `async-channel` and make `out-ch` an `async-channel` as well.
```racket
#lang racket/base

(require racket/async-channel)

(define num-workers 10)
(define num-orders  100)

(define  in-ch (make-async-channel))
(define out-ch (make-async-channel))

(define (worker-thread)
  (define num (async-channel-get in-ch))
  (sleep (random))  ; for up to 1 full second
  (async-channel-put out-ch num)
  (worker-thread))

(define workers (build-list num-workers (λ _ (thread worker-thread))))

(for ([i num-orders]) (async-channel-put in-ch i))
(for ([_ num-orders]) (async-channel-get out-ch))
```

From the first order to the last, the workers never have to wait to get orders or put results. This one takes around 6 seconds on my computer.

**What does any of this have to with events?**

If I replace `sleep` with `alarm-evt` inside `worker-thread`, Racket knows it can ignore the thread until the `alarm-evt` becomes ready for synchronization.
```racket
(define (worker-thread)
  (define num (async-channel-get in-ch))
  (sync (alarm-evt (+ (current-inexact-milliseconds) (random 1000))))
  (async-channel-put out-ch num)
  (worker-thread))
```

With this version of `worker-thread`, my computer takes around 5.5 seconds to handle all 100 orders with 10 threads. Racket seems to get away with this sort of precise scheduling around events that either wait on other events or do heavy I/O. 

**How can Event-lang help?**

Say I wanted to handle results in small batches. One way I could do it is with Event-lang's `list-evt` combinator.
```racket
#lang racket/base

(require event
         racket/async-channel)

(define num-workers 10)
(define num-orders  100)

(define  in-ch (make-async-channel))
(define out-ch (make-async-channel))

(define (worker-thread)
  (define num (async-channel-get in-ch))
  (sync (alarm-evt (+ (current-inexact-milliseconds) (random 1000))))
  (async-channel-put out-ch num)
  (worker-thread))

(define workers (build-list num-workers (λ _ (thread worker-thread))))

(for ([i num-orders]) (async-channel-put in-ch i))

(define num-batches 10)
(define batch-size (/ num-orders num-batches))

(for ([_ num-batches])
  (writeln (sync (apply list-evt (build-list batch-size (λ _ out-ch))))))
```

This one still uses `async-channel`s and `alarm-evt` to keep everything fast, but at the bottom it builds a `list-evt` with 10 copies of `out-ch` as its arguments. Each successful `sync` returns a list of 10 results instead of just one at a time. This version takes 6 seconds to handle 100 orders with 10 threads, but 250 milliseconds of it is the fixed cost of loading Algebraic Racket (which Event-lang uses internally).

And since I'm already loading Algebraic Racket, I might as well take advantage of it, too.

**How can Algebraic Racket help?**

Since every action in `worker-thread` involves actions with equivalent synchronizable events, I can use the `event-monad` and Algebraic Racket's `do`-notation to express `worker-thread` as a single event.
```racket
#lang algebraic/racket/base

(require algebraic/class/monad
         algebraic/data/event
         event
         racket/async-channel)

(instantiate event-monad)

(define num-workers 10)
(define num-orders  100)

(define  in-ch (make-async-channel))
(define out-ch (make-async-channel))

(define (worker-thread)
  (sync (do (num) <- in-ch
            (alarm-evt (+ (current-inexact-milliseconds) (random 1000)))
            (async-channel-put-evt out-ch num)))
  (worker-thread))

(define workers (build-list num-workers (λ _ (thread worker-thread))))

(for ([i num-orders]) (async-channel-put in-ch i))

(define num-batches 10)
(define batch-size (/ num-orders num-batches))

(for ([_ num-batches])
  (sync (apply list-evt (build-list batch-size (λ _ out-ch)))))
```

Here, I've changed the top line to `#lang algebraic/racket/base`, imported Algebraic Racket's `event-monad` and `do`-notation, and `instantiate`d the monad for the duration of the module. The `worker-thread` function body first synchronizes `in-ch` and binds the synchronization result to `num`. Then, it synchronizes the `alarm-evt` and discards its synchronization result. Finally, it puts `num` into `out-ch`. Not only is this version easier to read, but it's just as fast as the last one.

**But what about place channels?!?**

Most of what I've said about `async-channel`s applies to places and place channels, with one wrinkle. Here's a places adaptation of the version with `async-channel`s and `sleep`:
```racket
#lang racket/base

(require racket/place)

(provide main)

(define num-places 2)
(define num-workers 10)
(define num-orders 100)

(define (main)
  (define (make-workers-place)
    (place pch
      (define (worker-thread)
        (define num (place-channel-get pch))
        (sleep (random))
        (place-channel-put pch num)
        (worker-thread))
      (apply sync (build-list num-workers (λ _ (thread worker-thread))))))

  (define places (build-list num-places (λ _ (make-workers-place))))

  (for ([i num-orders])
    (if (even? i)
        (place-channel-put (car places) i)
        (place-channel-put (cadr places) i)))

  (for ([_ num-orders]) (apply sync places)))
```
The wrinkle is that I can't actually use `async-channels` anymore. They can't traverse place boundaries or place channels. Instead, the supervisor chooses an element of `places` for each order with a simple round-robin scheduler, and inside the places, workers get orders from the place channel `pch`.

This computer has 2 cores, so I start a place for each core. The places spawn 10 workers each, so that's 20 workers total. At 100 orders, this version takes around 4.5 seconds on my computer
. That's a full 1.5 seconds (35%) faster than its `async-channel`s counterpart.

But can we do better? If I replace `sleep` with `alarm-evt` again, my computer takes around 4 seconds. That's only a slight improvement over the `sleep` version, but it's also two full seconds (33%) *faster* than `async-channel`s with the `alarm-evt` optimization.

Here's a version with all the bells and whistles:
```racket
#lang algebraic/racket/base

(require algebraic/class/monad
         algebraic/data/event
         event
         racket/place)

(provide main)

(instantiate event-monad)

(define num-places 2)
(define num-workers 10)
(define num-orders 1000)

(define (main)
  (define (make-workers-place)
    (place ch
      (define (worker-thread)
        (sync (do (num) <- ch
                  (alarm-evt (+ (current-inexact-milliseconds) (random 1000)))
                  (thread (λ () (place-channel-put ch num)))))
        (worker-thread))
      (apply sync (build-list num-workers (λ _ (thread worker-thread))))))

  (define places (build-list num-places (λ _ (make-workers-place))))

  (for ([i num-orders])
    (if (even? i)
        (place-channel-put (car places) i)
        (place-channel-put (cadr places) i)))

  (define num-batches 10)
  (define batch-size (/ num-orders num-batches))

  (for ([_ num-batches])
    (sync (apply list-evt (build-list batch-size (λ _ (apply choice-evt places)))))))
```

At 100 orders, the trouble of starting two places and communicating through place channels might outweigh the benefit. But at 1,000 orders, `async-channel`s + `alarm-evt` + `list-evt` + `event-monad` takes 52 seconds, while places + all that other stuff takes 27 seconds, so places are around 25 seconds (48%) faster under the heavier load, which is about what I'd expect to see after doubling the number of hardware threads.

**In closing...**

If your application relies heavily on interrupt-driven data sources like network sockets or user input devices, it migh perform better with judicious application of events. Event-lang provides combinators to make working with events and their synchronization results as simple as possible, and the `event-monad` provides a framework for composing events and event combinators.

**Comment by dedbox** [comment]
Sorry, I realize I forgot to convert `(random)` from secon ds to milliseconds in the `alarm-evt` examples and am updating my response now.

**Comment by dedbox** [comment]
Updated. This is the conclusion I was expecting.

**Comment by mbutterick** [comment]
Thanks for the detailed examples! I will study.
